# Generated by Django 5.0.6 on 2026-09-08 17:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharterStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot"),
                            ("SHORT_TERM", "Short-term"),
                            ("MEDIUM_TERM", "Medium-term"),
                            ("MULTI_VOYAGE", "Multi-voyage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charter_strategies",
                        to="catalog.cargorequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "port_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bunker_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "demurrage_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot"),
                            ("SHORT_TERM", "Short-term"),
                            ("MEDIUM_TERM", "Medium-term"),
                            ("MULTI_VOYAGE", "Multi-voyage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "total_quantity_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="total quantity (t)",
                    ),
                ),
                ("number_of_voyages", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("proposed", "Proposed"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_plans",
                        to="catalog.cargorequirement",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_plans",
                        to="decisions.charterstrategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("sourcing", "Multi-origin sourcing"),
                            ("laycan", "Laycan optimization"),
                            ("contract", "Contract-type selection"),
                            ("idle_vessel", "Idle-vessel employment"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("solver", models.CharField(blank=True, max_length=80)),
                ("solver_version", models.CharField(blank=True, max_length=40)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_runs",
                        to="catalog.cargorequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "port_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bunker_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "demurrage_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("is_optimal", models.BooleanField(default=False)),
                (
                    "objective_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "contract_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_results",
                        to="decisions.contractplan",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_results",
                        to="decisions.charterstrategy",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="decisions.optimizationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "rank"],
            },
        ),
        migrations.CreateModel(
            name="PortCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "port_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bunker_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "demurrage_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "suitability_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_compatible", models.BooleanField(default=True)),
                (
                    "landed_cost_delta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_candidates",
                        to="catalog.cargorequirement",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="catalog.port",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-suitability_score"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_baseline", models.BooleanField(default=False)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="catalog.cargorequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="optimizationrun",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="optimization_runs",
                to="decisions.scenario",
            ),
        ),
        migrations.CreateModel(
            name="VoyagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "port_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bunker_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "demurrage_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "quantity_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantity (t)",
                    ),
                ),
                ("laycan_start", models.DateField(blank=True, null=True)),
                ("laycan_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("proposed", "Proposed"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyage_plans",
                        to="catalog.cargorequirement",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voyage_plans",
                        to="catalog.route",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyage_plans",
                        to="decisions.charterstrategy",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voyage_plans",
                        to="catalog.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VesselCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "port_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bunker_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "demurrage_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "suitability_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_compatible", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cargo_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_candidates",
                        to="catalog.cargorequirement",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="catalog.vessel",
                    ),
                ),
                (
                    "voyage_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_candidates",
                        to="decisions.voyageplan",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-suitability_score"],
            },
        ),
        migrations.CreateModel(
            name="ContractVoyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Order of this voyage within the contract."
                    ),
                ),
                (
                    "contract_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_voyages",
                        to="decisions.contractplan",
                    ),
                ),
                (
                    "voyage_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_voyages",
                        to="decisions.voyageplan",
                    ),
                ),
            ],
            options={
                "ordering": ["contract_plan", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="charterstrategy",
            index=models.Index(fields=["cargo_requirement"], name="strategy_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="charterstrategy",
            index=models.Index(fields=["strategy_type"], name="strategy_type_idx"),
        ),
        migrations.AddIndex(
            model_name="contractplan",
            index=models.Index(fields=["cargo_requirement"], name="contract_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="contractplan",
            index=models.Index(fields=["strategy_type"], name="contract_strategy_idx"),
        ),
        migrations.AddIndex(
            model_name="contractplan",
            index=models.Index(fields=["status"], name="contract_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("period_start__isnull", True),
                    ("period_end__isnull", True),
                    ("period_end__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="ck_contractplan_period_order",
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationresult",
            index=models.Index(fields=["run", "rank"], name="optresult_run_rank_idx"),
        ),
        migrations.AddIndex(
            model_name="optimizationresult",
            index=models.Index(fields=["is_optimal"], name="optresult_optimal_idx"),
        ),
        migrations.AddConstraint(
            model_name="optimizationresult",
            constraint=models.UniqueConstraint(
                fields=("run", "rank"), name="uq_optresult_run_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="portcandidate",
            index=models.Index(fields=["cargo_requirement"], name="pcand_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="portcandidate",
            index=models.Index(fields=["port"], name="pcand_port_idx"),
        ),
        migrations.AddConstraint(
            model_name="portcandidate",
            constraint=models.UniqueConstraint(
                fields=("cargo_requirement", "port"), name="uq_portcandidate_natural"
            ),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["cargo_requirement"], name="scenario_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["is_baseline"], name="scenario_baseline_idx"),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(
                fields=["run_type", "-created_at"], name="optrun_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(fields=["cargo_requirement"], name="optrun_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(fields=["scenario"], name="optrun_scenario_idx"),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(fields=["status"], name="optrun_status_idx"),
        ),
        migrations.AddIndex(
            model_name="voyageplan",
            index=models.Index(fields=["cargo_requirement"], name="voyage_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="voyageplan",
            index=models.Index(fields=["route"], name="voyage_route_idx"),
        ),
        migrations.AddIndex(
            model_name="voyageplan",
            index=models.Index(fields=["vessel"], name="voyage_vessel_idx"),
        ),
        migrations.AddIndex(
            model_name="voyageplan",
            index=models.Index(fields=["status"], name="voyage_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="voyageplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("laycan_start__isnull", True),
                    ("laycan_end__isnull", True),
                    ("laycan_end__gte", models.F("laycan_start")),
                    _connector="OR",
                ),
                name="ck_voyageplan_laycan_order",
            ),
        ),
        migrations.AddIndex(
            model_name="vesselcandidate",
            index=models.Index(fields=["cargo_requirement"], name="vcand_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="vesselcandidate",
            index=models.Index(fields=["vessel"], name="vcand_vessel_idx"),
        ),
        migrations.AddIndex(
            model_name="vesselcandidate",
            index=models.Index(fields=["voyage_plan"], name="vcand_voyage_idx"),
        ),
        migrations.AddConstraint(
            model_name="vesselcandidate",
            constraint=models.UniqueConstraint(
                fields=("cargo_requirement", "vessel", "voyage_plan"),
                name="uq_vesselcandidate_natural",
            ),
        ),
        migrations.AddIndex(
            model_name="contractvoyage",
            index=models.Index(fields=["contract_plan"], name="cv_contract_idx"),
        ),
        migrations.AddIndex(
            model_name="contractvoyage",
            index=models.Index(fields=["voyage_plan"], name="cv_voyage_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractvoyage",
            constraint=models.UniqueConstraint(
                fields=("contract_plan", "voyage_plan"),
                name="uq_contractvoyage_plan_voyage",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractvoyage",
            constraint=models.UniqueConstraint(
                fields=("contract_plan", "sequence"), name="uq_contractvoyage_sequence"
            ),
        ),
    ]
