# Generated by Django 5.0.6 on 2026-09-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_port_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("freight_increase", "Freight increase"),
                            ("freight_decrease", "Freight decrease"),
                            ("freight_volatility", "Freight volatility"),
                            ("congestion_increase", "Congestion increase"),
                            ("cyclone_warning", "Cyclone warning"),
                            ("marine_warning", "Marine warning"),
                            ("vessel_scarcity", "Vessel scarcity"),
                            ("eta_delay", "ETA delay"),
                            ("port_incompatibility", "Port incompatibility"),
                            ("unusual_market_pressure", "Unusual market pressure"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("entity", models.CharField(blank=True, max_length=200)),
                (
                    "trigger_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("recommended_action", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="catalog.port",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="catalog.route",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="catalog.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("database", "Database"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=500)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type", "-timestamp"], name="alert_type_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "-timestamp"], name="alert_status_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity", "-timestamp"], name="alert_sev_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["dedup_key"], name="alert_dedup_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["alert", "channel"], name="notif_alert_chan_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "-created_at"], name="notif_status_idx"
            ),
        ),
    ]
