# Generated by Django 5.0.6 on 2026-09-08 17:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETAForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField()),
                ("predicted_eta", models.DateTimeField()),
                (
                    "uncertainty_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="uncertainty (h)",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="FreightForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vessel_type", models.CharField(blank=True, max_length=14)),
                ("generated_at", models.DateTimeField()),
                ("target_date", models.DateField()),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("short_term", "Short-term (days-weeks)"),
                            ("medium_term", "Medium-term (weeks-months)"),
                        ],
                        default="short_term",
                        max_length=12,
                    ),
                ),
                (
                    "predicted_rate_per_tonne",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="predicted rate/t",
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-generated_at", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="MarineObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "significant_wave_height_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="sig. wave height (m)",
                    ),
                ),
                (
                    "wave_period_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="wave period (s)",
                    ),
                ),
                (
                    "swell_direction_deg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("360")),
                        ],
                        verbose_name="swell dir (deg)",
                    ),
                ),
                (
                    "current_speed_kn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="current speed (kn)",
                    ),
                ),
                (
                    "sea_surface_temp_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="SST (C)",
                    ),
                ),
                ("is_forecast", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PortCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("arrival_at", models.DateTimeField(blank=True, null=True)),
                ("berthed_at", models.DateTimeField(blank=True, null=True)),
                ("departure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("arrival", "Arrival (anchorage)"),
                            ("berthed", "Berthed"),
                            ("departure", "Departure"),
                        ],
                        default="arrival",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-arrival_at"],
            },
        ),
        migrations.CreateModel(
            name="PortCongestionObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField()),
                ("vessels_waiting", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_wait_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="avg wait (days)",
                    ),
                ),
                (
                    "berth_occupancy_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="berth occupancy (%)",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("is_estimated", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("market_entry", "Market-entry timing"),
                            ("contract_type", "Contract type"),
                            ("laycan", "Laycan window"),
                            ("alt_port", "Alternative port"),
                            ("sourcing", "Multi-origin sourcing"),
                            ("idle_vessel", "Idle-vessel employment"),
                        ],
                        max_length=14,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("summary", models.CharField(max_length=255)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "estimated_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("explanation", models.JSONField(blank=True, default=dict)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("demurrage", "Demurrage"),
                            ("weather", "Weather / marine"),
                            ("congestion", "Port congestion"),
                            ("geopolitical", "Geopolitical / disruption"),
                        ],
                        max_length=14,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=6,
                    ),
                ),
                ("drivers", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reporter_country", models.CharField(blank=True, max_length=80)),
                ("partner_country", models.CharField(blank=True, max_length=80)),
                (
                    "period",
                    models.DateField(help_text="First day of the reporting period."),
                ),
                (
                    "quantity_tonnes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantity (t)",
                    ),
                ),
                (
                    "trade_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="trade value",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("source", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "wind_speed_kn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="wind speed (kn)",
                    ),
                ),
                (
                    "wind_dir_deg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("360")),
                        ],
                        verbose_name="wind dir (deg)",
                    ),
                ),
                (
                    "precipitation_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="precipitation (mm)",
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="temperature (C)",
                    ),
                ),
                ("is_forecast", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AISPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "sog",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="SOG (kn)",
                    ),
                ),
                (
                    "cog",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("360")),
                        ],
                        verbose_name="COG (deg)",
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("360")),
                        ],
                        verbose_name="heading (deg)",
                    ),
                ),
                ("nav_status", models.CharField(blank=True, max_length=64)),
                ("source", models.CharField(blank=True, max_length=64)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="catalog.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BunkerPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hub", models.CharField(blank=True, max_length=80)),
                (
                    "fuel_grade",
                    models.CharField(
                        choices=[
                            ("vlsfo", "VLSFO"),
                            ("hsfo", "HSFO"),
                            ("mgo", "MGO"),
                            ("lsmgo", "LSMGO"),
                        ],
                        default="vlsfo",
                        max_length=8,
                    ),
                ),
                ("observed_on", models.DateField()),
                (
                    "price_per_tonne",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="price/t",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("source", models.CharField(blank=True, max_length=64)),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bunker_prices",
                        to="catalog.port",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_on"],
            },
        ),
        migrations.CreateModel(
            name="CommodityPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_on", models.DateField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit", models.CharField(default="tonne", max_length=16)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("is_estimated", models.BooleanField(default=False)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="catalog.commodity",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_on"],
            },
        ),
        migrations.CreateModel(
            name="CycloneObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("system_name", models.CharField(max_length=120)),
                ("advisory_no", models.CharField(blank=True, max_length=32)),
                ("timestamp", models.DateTimeField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("depression", "Depression"),
                            ("cyclonic_storm", "Cyclonic Storm"),
                            ("severe", "Severe Cyclonic Storm"),
                            ("very_severe", "Very Severe Cyclonic Storm"),
                            ("super", "Super Cyclonic Storm"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                (
                    "max_wind_kn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="max wind (kn)",
                    ),
                ),
                (
                    "central_pressure_hpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="central pressure (hPa)",
                    ),
                ),
                ("is_forecast", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["system_name", "-timestamp"], name="cyclone_system_idx"
                    ),
                    models.Index(fields=["timestamp"], name="cyclone_ts_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cycloneobservation",
            constraint=models.UniqueConstraint(
                fields=("system_name", "timestamp", "source"),
                name="uq_cyclone_system_ts_source",
            ),
        ),
        migrations.AddField(
            model_name="etaforecast",
            name="destination_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eta_forecasts",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="etaforecast",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eta_forecasts",
                to="catalog.route",
            ),
        ),
        migrations.AddField(
            model_name="etaforecast",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eta_forecasts",
                to="catalog.vessel",
            ),
        ),
        migrations.AddField(
            model_name="freightforecast",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freight_forecasts",
                to="catalog.route",
            ),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marine_observations",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="portcall",
            name="berth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="port_calls",
                to="catalog.berth",
            ),
        ),
        migrations.AddField(
            model_name="portcall",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_calls",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="portcall",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_calls",
                to="catalog.vessel",
            ),
        ),
        migrations.AddField(
            model_name="portcongestionobservation",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="congestion_observations",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="cargo_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="catalog.cargorequirement",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="destination_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="catalog.origin",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="catalog.route",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="catalog.vessel",
            ),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="cargo_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_scores",
                to="catalog.cargorequirement",
            ),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_scores",
                to="catalog.origin",
            ),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_scores",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_scores",
                to="catalog.route",
            ),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_scores",
                to="catalog.vessel",
            ),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_observations",
                to="catalog.commodity",
            ),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="destination_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trade_observations",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trade_observations",
                to="catalog.origin",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weather_observations",
                to="catalog.port",
            ),
        ),
        migrations.AddIndex(
            model_name="aisposition",
            index=models.Index(
                fields=["vessel", "-timestamp"], name="ais_vessel_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisposition",
            index=models.Index(fields=["timestamp"], name="ais_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="aisposition",
            constraint=models.UniqueConstraint(
                fields=("vessel", "timestamp"), name="uq_ais_vessel_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="bunkerpriceobservation",
            index=models.Index(fields=["port", "-observed_on"], name="bunker_port_idx"),
        ),
        migrations.AddIndex(
            model_name="bunkerpriceobservation",
            index=models.Index(
                fields=["fuel_grade", "-observed_on"], name="bunker_grade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bunkerpriceobservation",
            index=models.Index(fields=["observed_on"], name="bunker_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="bunkerpriceobservation",
            constraint=models.UniqueConstraint(
                fields=("port", "hub", "fuel_grade", "observed_on", "source"),
                name="uq_bunker_natural",
            ),
        ),
        migrations.AddIndex(
            model_name="commoditypriceobservation",
            index=models.Index(
                fields=["commodity", "-observed_on"], name="commprice_comm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commoditypriceobservation",
            index=models.Index(fields=["observed_on"], name="commprice_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="commoditypriceobservation",
            constraint=models.UniqueConstraint(
                fields=("commodity", "observed_on", "source"),
                name="uq_commprice_natural",
            ),
        ),
        migrations.AddIndex(
            model_name="etaforecast",
            index=models.Index(
                fields=["vessel", "-generated_at"], name="eta_vessel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etaforecast",
            index=models.Index(
                fields=["destination_port", "-generated_at"], name="eta_dest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etaforecast",
            index=models.Index(fields=["predicted_eta"], name="eta_predicted_idx"),
        ),
        migrations.AddIndex(
            model_name="etaforecast",
            index=models.Index(fields=["generated_at"], name="eta_generated_idx"),
        ),
        migrations.AddIndex(
            model_name="freightforecast",
            index=models.Index(
                fields=["route", "target_date"], name="ff_route_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freightforecast",
            index=models.Index(fields=["generated_at"], name="ff_generated_idx"),
        ),
        migrations.AddIndex(
            model_name="freightforecast",
            index=models.Index(fields=["target_date"], name="ff_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="freightforecast",
            constraint=models.UniqueConstraint(
                fields=(
                    "route",
                    "vessel_type",
                    "target_date",
                    "horizon",
                    "model_name",
                    "model_version",
                ),
                name="uq_freight_forecast_natural",
            ),
        ),
        migrations.AddIndex(
            model_name="marineobservation",
            index=models.Index(
                fields=["port", "-timestamp"], name="marine_port_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marineobservation",
            index=models.Index(fields=["timestamp"], name="marine_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="portcall",
            index=models.Index(
                fields=["vessel", "-arrival_at"], name="portcall_vessel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portcall",
            index=models.Index(
                fields=["port", "-arrival_at"], name="portcall_port_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portcall",
            index=models.Index(fields=["arrival_at"], name="portcall_arrival_idx"),
        ),
        migrations.AddIndex(
            model_name="portcongestionobservation",
            index=models.Index(
                fields=["port", "-observed_at"], name="cong_port_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portcongestionobservation",
            index=models.Index(fields=["observed_at"], name="cong_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="portcongestionobservation",
            constraint=models.UniqueConstraint(
                fields=("port", "observed_at", "source"),
                name="uq_congestion_port_ts_source",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["rec_type", "-generated_at"], name="rec_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["cargo_requirement", "-generated_at"], name="rec_cargo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["route", "-generated_at"], name="rec_route_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["origin", "-generated_at"], name="rec_origin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["destination_port", "-generated_at"], name="rec_dest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["vessel", "-generated_at"], name="rec_vessel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["generated_at"], name="rec_generated_idx"),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["risk_type", "-generated_at"], name="risk_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["route", "-generated_at"], name="risk_route_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(fields=["port", "-generated_at"], name="risk_port_idx"),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["vessel", "-generated_at"], name="risk_vessel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["origin", "-generated_at"], name="risk_origin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(fields=["generated_at"], name="risk_generated_idx"),
        ),
        migrations.AddIndex(
            model_name="tradeobservation",
            index=models.Index(
                fields=["commodity", "-period"], name="trade_comm_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeobservation",
            index=models.Index(fields=["origin"], name="trade_origin_idx"),
        ),
        migrations.AddIndex(
            model_name="tradeobservation",
            index=models.Index(fields=["destination_port"], name="trade_dest_idx"),
        ),
        migrations.AddIndex(
            model_name="tradeobservation",
            index=models.Index(fields=["period"], name="trade_period_idx"),
        ),
        migrations.AddIndex(
            model_name="weatherobservation",
            index=models.Index(fields=["port", "-timestamp"], name="wx_port_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="weatherobservation",
            index=models.Index(fields=["timestamp"], name="wx_ts_idx"),
        ),
    ]
