# Generated by Django 5.0.6 on 2026-09-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aisposition",
            name="uq_ais_vessel_ts",
        ),
        migrations.AddField(
            model_name="aisposition",
            name="mmsi",
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AddField(
            model_name="aisposition",
            name="vessel_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="aisposition",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="catalog.vessel",
            ),
        ),
        migrations.AddIndex(
            model_name="aisposition",
            index=models.Index(fields=["mmsi", "-timestamp"], name="ais_mmsi_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="aisposition",
            constraint=models.UniqueConstraint(
                fields=("mmsi", "timestamp"), name="uq_ais_mmsi_ts"
            ),
        ),
    ]
