# Generated by Django 5.0.6 on 2026-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        (
            "operations",
            "0002_remove_aisposition_uq_ais_vessel_ts_aisposition_mmsi_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aisposition",
            name="uq_ais_mmsi_ts",
        ),
        migrations.AddConstraint(
            model_name="aisposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mmsi", ""), _negated=True),
                fields=("mmsi", "timestamp"),
                name="uq_ais_mmsi_ts",
            ),
        ),
        migrations.AddConstraint(
            model_name="aisposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mmsi", "")),
                fields=("vessel", "timestamp"),
                name="uq_ais_vessel_ts",
            ),
        ),
    ]
