# Generated by Django 5.0.6 on 2026-09-09 07:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        ("operations", "0003_remove_aisposition_uq_ais_mmsi_ts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commoditypriceobservation",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commoditypriceobservation",
            name="source_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commoditypriceobservation",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="source_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="commoditypriceobservation",
            name="source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="tradeobservation",
            name="source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="PortTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(help_text="First day of the reporting period."),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("total", "Total / unspecified"),
                        ],
                        default="total",
                        max_length=8,
                    ),
                ),
                (
                    "throughput_tonnes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="throughput (t)",
                    ),
                ),
                ("vessel_count", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("source_date", models.DateField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="port_traffic",
                        to="catalog.commodity",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_observations",
                        to="catalog.port",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "indexes": [
                    models.Index(
                        fields=["port", "-period"], name="porttraffic_port_idx"
                    ),
                    models.Index(fields=["period"], name="porttraffic_period_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="porttraffic",
            constraint=models.UniqueConstraint(
                fields=("port", "commodity", "period", "direction", "source"),
                name="uq_porttraffic_natural",
            ),
        ),
    ]
