# Generated by Django 5.0.6 on 2026-09-09 07:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        ("operations", "0004_commoditypriceobservation_retrieved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeobservation",
            name="flow",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("export", "Export"),
                    ("re_import", "Re-import"),
                    ("re_export", "Re-export"),
                ],
                default="import",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="hs_code",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="net_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="net weight (kg)",
            ),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="qty_unit",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="tradeobservation",
            name="raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="tradeobservation",
            index=models.Index(fields=["hs_code", "-period"], name="trade_hs_idx"),
        ),
    ]
