# Generated by Django 5.0.6 on 2026-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        ("operations", "0005_tradeobservation_flow_tradeobservation_hs_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherobservation",
            name="raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="weather_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="weather_condition",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="weatherobservation",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "timestamp", "source"),
                name="uq_weather_loc_ts_source",
            ),
        ),
    ]
