# Generated by Django 5.0.6 on 2026-09-09 08:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
        ("operations", "0006_weatherobservation_raw_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cycloneobservation",
            name="uq_cyclone_system_ts_source",
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="bulletin_kind",
            field=models.CharField(
                choices=[
                    ("track", "Cyclone track"),
                    ("wind_warning", "Cyclone wind warning"),
                ],
                default="track",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="gust_kn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="gust (kn)",
            ),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="issue_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="severity",
            field=models.CharField(
                choices=[
                    ("none", "No warning"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("severe", "Severe"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="source_ref",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cycloneobservation",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="area_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="headline",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="issue_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="severity",
            field=models.CharField(
                choices=[
                    ("none", "No warning"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("severe", "Severe"),
                    ("unknown", "Unknown"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="source_ref",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marineobservation",
            name="warning_type",
            field=models.CharField(
                choices=[
                    ("port_warning", "Port warning"),
                    ("sea_area_bulletin", "Sea area bulletin"),
                    ("coastal_bulletin", "Coastal bulletin"),
                    ("observation", "Ocean-state observation"),
                    ("other", "Other"),
                ],
                default="observation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cycloneobservation",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90")),
                    django.core.validators.MaxValueValidator(Decimal("90")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cycloneobservation",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180")),
                    django.core.validators.MaxValueValidator(Decimal("180")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marineobservation",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90")),
                    django.core.validators.MaxValueValidator(Decimal("90")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marineobservation",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180")),
                    django.core.validators.MaxValueValidator(Decimal("180")),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="marineobservation",
            index=models.Index(
                fields=["warning_type", "-timestamp"], name="marine_warn_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cycloneobservation",
            constraint=models.UniqueConstraint(
                fields=("system_name", "timestamp", "bulletin_kind", "source"),
                name="uq_cyclone_system_ts_source",
            ),
        ),
    ]
