# Generated by Django 5.0.6 on 2026-09-09 10:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0007_remove_cycloneobservation_uq_cyclone_system_ts_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="freightforecast",
            name="confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
