# Generated by Django 5.0.6 on 2026-09-08 17:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreightObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vessel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("handysize", "Handysize"),
                            ("supramax", "Supramax"),
                            ("ultramax", "Ultramax"),
                            ("panamax", "Panamax"),
                            ("kamsarmax", "Kamsarmax"),
                            ("post_panamax", "Post-Panamax"),
                            ("capesize", "Capesize"),
                            ("other", "Other"),
                        ],
                        max_length=14,
                    ),
                ),
                ("observed_on", models.DateField(db_index=True)),
                (
                    "rate_per_tonne",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="rate/t",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot"),
                            ("index", "Index"),
                            ("fixture", "Reported fixture"),
                            ("estimate", "Estimated / proxy"),
                        ],
                        default="spot",
                        max_length=8,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("is_estimated", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-observed_on"],
            },
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("country", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distance_nm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="distance (nm)",
                    ),
                ),
                (
                    "typical_transit_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="typical transit (days)",
                    ),
                ),
            ],
            options={
                "ordering": ["origin__name", "destination_port__name"],
            },
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imo",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IMO number must be exactly 7 digits.",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="IMO number",
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MMSI must be exactly 9 digits.",
                                regex="^\\d{9}$",
                            )
                        ],
                        verbose_name="MMSI",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "vessel_type",
                    models.CharField(
                        choices=[
                            ("handysize", "Handysize"),
                            ("supramax", "Supramax"),
                            ("ultramax", "Ultramax"),
                            ("panamax", "Panamax"),
                            ("kamsarmax", "Kamsarmax"),
                            ("post_panamax", "Post-Panamax"),
                            ("capesize", "Capesize"),
                            ("other", "Other"),
                        ],
                        default="panamax",
                        max_length=14,
                    ),
                ),
                (
                    "dwt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="DWT (t)",
                    ),
                ),
                (
                    "loa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="LOA (m)",
                    ),
                ),
                (
                    "beam",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="beam (m)",
                    ),
                ),
                (
                    "draft",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="draft (m)",
                    ),
                ),
                ("flag", models.CharField(blank=True, max_length=80)),
                (
                    "year_built",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="service speed (kn)",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coal_thermal", "Coal — Thermal"),
                            ("coal_coking", "Coal — Coking"),
                            ("iron_ore", "Iron Ore"),
                            ("bauxite", "Bauxite"),
                            ("fertilizer", "Fertilizer"),
                            ("grain", "Grain"),
                            ("other", "Other"),
                        ],
                        default="coal_thermal",
                        max_length=20,
                    ),
                ),
                ("hs_code", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "commodities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["category"], name="commodity_category_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Berth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("berth_name", models.CharField(max_length=120)),
                (
                    "max_loa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="max LOA (m)",
                    ),
                ),
                (
                    "max_beam",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="max beam (m)",
                    ),
                ),
                (
                    "max_draft",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="max draft (m)",
                    ),
                ),
                (
                    "handling_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="handling rate (t/day)",
                    ),
                ),
                ("special_constraints", models.JSONField(blank=True, default=dict)),
                (
                    "supported_commodities",
                    models.ManyToManyField(
                        blank=True, related_name="berths", to="catalog.commodity"
                    ),
                ),
            ],
            options={
                "ordering": ["port__name", "berth_name"],
            },
        ),
        migrations.CreateModel(
            name="CargoRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=64, unique=True)),
                (
                    "quantity_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantity (t)",
                    ),
                ),
                (
                    "tolerance_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="tolerance (%)",
                    ),
                ),
                ("laycan_start", models.DateField()),
                ("laycan_end", models.DateField()),
                (
                    "target_price_per_tonne",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="target price/t",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("planned", "Planned"),
                            ("fixed", "Fixed"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargo_requirements",
                        to="catalog.commodity",
                    ),
                ),
                (
                    "preferred_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargo_requirements",
                        to="catalog.origin",
                    ),
                ),
            ],
            options={
                "ordering": ["-laycan_start"],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=80)),
                ("unlocode", models.CharField(blank=True, max_length=5)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "port_type",
                    models.CharField(
                        choices=[
                            ("seaport", "Seaport"),
                            ("river", "River port"),
                            ("anchorage", "Anchorage / lightening"),
                            ("terminal", "Private terminal"),
                        ],
                        default="seaport",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["country"], name="port_country_idx"),
                    models.Index(fields=["port_type"], name="port_type_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="port",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="uq_port_name_country"
            ),
        ),
        migrations.AddField(
            model_name="origin",
            name="load_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origins",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="cargorequirement",
            name="destination_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargo_requirements",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="berths",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_routes",
                to="catalog.port",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="catalog.origin",
            ),
        ),
        migrations.AddField(
            model_name="freightobservation",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freight_observations",
                to="catalog.route",
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["vessel_type"], name="vessel_type_idx"),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["name"], name="vessel_name_idx"),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["dwt"], name="vessel_dwt_idx"),
        ),
        migrations.AddIndex(
            model_name="origin",
            index=models.Index(fields=["country"], name="origin_country_idx"),
        ),
        migrations.AddIndex(
            model_name="cargorequirement",
            index=models.Index(fields=["status"], name="cargo_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cargorequirement",
            index=models.Index(fields=["destination_port"], name="cargo_dest_idx"),
        ),
        migrations.AddIndex(
            model_name="cargorequirement",
            index=models.Index(
                fields=["laycan_start", "laycan_end"], name="cargo_laycan_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cargorequirement",
            constraint=models.CheckConstraint(
                check=models.Q(("laycan_end__gte", models.F("laycan_start"))),
                name="ck_cargo_laycan_order",
            ),
        ),
        migrations.AddIndex(
            model_name="berth",
            index=models.Index(fields=["port"], name="berth_port_idx"),
        ),
        migrations.AddIndex(
            model_name="berth",
            index=models.Index(fields=["max_draft"], name="berth_max_draft_idx"),
        ),
        migrations.AddConstraint(
            model_name="berth",
            constraint=models.UniqueConstraint(
                fields=("port", "berth_name"), name="uq_berth_port_name"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["origin"], name="route_origin_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["destination_port"], name="route_dest_idx"),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("origin", "destination_port"),
                name="uq_route_origin_destination",
            ),
        ),
        migrations.AddIndex(
            model_name="freightobservation",
            index=models.Index(
                fields=["route", "observed_on"], name="freight_route_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freightobservation",
            index=models.Index(fields=["rate_type"], name="freight_rate_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="freightobservation",
            constraint=models.UniqueConstraint(
                fields=("route", "vessel_type", "observed_on", "rate_type", "source"),
                name="uq_freight_obs_natural",
            ),
        ),
    ]
