# Generated by Django 5.0.6 on 2026-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="coast",
            field=models.CharField(
                choices=[
                    ("east_coast_india", "East Coast (India)"),
                    ("west_coast_india", "West Coast (India)"),
                    ("overseas", "Overseas (origin)"),
                    ("other", "Other"),
                ],
                default="east_coast_india",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(fields=["coast"], name="port_coast_idx"),
        ),
    ]
