# Generated by Django 5.0.6 on 2026-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_east_coast_ports"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("open", "Open / available"),
                    ("laden", "Laden (on voyage)"),
                    ("ballast", "Ballast (repositioning)"),
                    ("fixed", "Fixed (committed)"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["availability_status"], name="vessel_avail_idx"),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["draft"], name="vessel_draft_idx"),
        ),
    ]
