# Generated by Django 5.0.6 on 2026-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_vessel_availability_status_vessel_open_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
