# Generated by Django 5.0.6 on 2026-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_port_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
