# Generated by Django 5.0.6 on 2026-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(db_index=True, max_length=100)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("rest", "REST API"),
                            ("file", "File"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.PositiveIntegerField(default=0)),
                ("records_valid", models.PositiveIntegerField(default=0)),
                ("records_invalid", models.PositiveIntegerField(default=0)),
                ("records_written", models.PositiveIntegerField(default=0)),
                ("records_duplicate", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_key", "-created_at"], name="ingrun_source_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="ingrun_status_idx"
                    ),
                ],
            },
        ),
    ]
