# Generated by Django 5.0.6 on 2026-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("partial", "Partial success"),
                    ("failed", "Failed"),
                    ("source_unavailable", "Source unavailable"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
